hhit:
  #uploadPath: C:\var\files\
  uploadPath: /root/var/files/
logging:
  level:
    root: info
    com.hhit: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://address=(protocol=tcp)(host=2408:4004:1f0:d400:a89d:35f9:c90f:438e)(port=3306)/bootdo?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://127.0.0.1:3306/bootdo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
#    password: mysqlZx..00..
    password: saier@Am#n345 #saier@Am#n345
    initialSize: 40
    minIdle: 60
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    multiStatementAllow: true
    maxPoolPreparedStatementPerConnectionSize: 200
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
    cluster:
      nodes: 39.105.11.138:9738,45.76.21.124:7111,45.76.21.124:7112,45.76.21.124:7113,39.105.11.138:9737,39.105.11.138:9736
    jedis:
      pool:
        max-idle: 100
        min-idle: 10
        max-active: 30
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 39.105.11.138:9300



     